apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: profiler
#  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: profiler
  template:
    metadata:
      labels:
        app: profiler
      annotations: # add annotation for prometheus scraping
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9400'
        prometheus.io/path: '/metrics' #default is /metrics

    spec:
      serviceAccountName: admin-pod
      containers:
        - name: profiler-container
          image: centaurusinfra/profiler   
          resources:
              limits:
                memory: "2Gi"
                cpu: "1"
              requests:
                cpu: "0.5"
                memory: "1Gi"
          env:
            - name: PYTHONUNBUFFERED  #for python print show in kubernetes log
              value: "0"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP 
        - name: dcgm-container
          image: nvidia/dcgm-exporter:2.0.13-2.1.1-ubuntu18.04
          # switch default metrics to additional profiling metrics, not all gpu supported. if not support, container fatal error
          #args:
          #  - "-f=/etc/dcgm-exporter/dcp-metrics-included.csv"
          ports:
            - containerPort: 9400
          env:
            - name: DCGM_EXPORTER_INTERVAL
              value: "100"
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
---
#give the profiler pod admin rights to update cluster node annotation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-pod      
  namespace: default

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-pod
subjects:
  - kind: ServiceAccount
    name: admin-pod
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io      
