apiVersion: v1
kind: Pod
metadata:
  name: dcgm-pod
spec:
  containers:
    - name: dcgm-container
      image: nvidia/dcgm-exporter:2.0.13-2.1.1-ubuntu18.04
      ports:
        - containerPort: 9400
          hostPort: 9400
      env:
        - name: DCGM_EXPORTER_INTERVAL
          value: "100"
      securityContext:
        capabilities:
          add:
            - SYS_ADMIN
