apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: profiler
#  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: profiler
  template:
    metadata:
      labels:
        app: profiler
      annotations: # add annotation for prometheus scraping
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9400'
        prometheus.io/path: '/metrics' #default is /metrics

    spec:
      serviceAccountName: admin-pod
      containers:
        - name: profiler-container
          image: fizzbb/profiler:v1.1   
          imagePullPolicy: IfNotPresent  # use local build image, deployed node must have the image
          ports:
            - containerPort: 9999
              hostPort: 9999
          resources:
              limits:
                memory: "2Gi"
                cpu: "1"
              requests:
                cpu: "0.5"
                memory: "1Gi"
          env:
            - name: PYTHONUNBUFFERED  #for python print show in kubernetes log
              value: "0"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP 
        - name: dcgm-container
          image: nvidia/dcgm-exporter:2.0.13-2.1.1-ubuntu18.04
          ports:
            - containerPort: 9400
          env:
            - name: DCGM_EXPORTER_INTERVAL
              value: "100"
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
      
