---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alnair-datacache-operator
  labels:
    app: alnair-datacache-operator
spec:
  selector:
    matchLabels:
      app: alnair-datacache-operator
  template:
    metadata:
      labels:
        app: alnair-datacache-operator
    spec:

        #shareProcessNamespace: true

      containers:

      - name: alnair-datacache-k8s-operator-service
        image: parekhnikunj/alnair-datacache-k8s-operator

        envFrom:
            - secretRef:
                name: alnair-cache-operator-secret

        ports:
            - containerPort: 8002

        env:
          - name: res_namespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
#          - name: alluxio_master_host
#            value: 10.244.1.77
