---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alnair-datacache-resource-reader-role
  namespace: default
rules:
- apiGroups: [ "" ]
  resources:
  - pods
  - jobs
  - deployments
  verbs: [ get, list, create, update, delete, deletecollection, watch ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alnair-datacache-resource-reader-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alnair-datacache-resource-reader-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
