---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: alnair-datacaches.centaurusinfra.com
spec:
  scope: Namespaced  #Cluster
  group: centaurusinfra.com

  names:
    kind: AlnairDatacache
    singular: alnair-datacache
    plural: alnair-datacaches
    shortNames:
      - datacache
      - datacaches

  versions:
    - name: v1
      served: true # Enables/disables each version
      storage: true # Only one version marked storage
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cacheDataset:
                  type: boolean
                  description: "Boolean flag to accept weather data orchestration cache is to be used"

                replicas:
                  type: integer
                  minimum: 1

#              nodeName:
#                type: string
#                description: "Name of node the original training pod was intended to run on"

                #affinity here:

            #reapiextensions.k8s.io/v1quired: ["cacheDataset"] # Is not currently mandatory
          required: ["spec"]
