apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-daemonset
  namespace: alnair
spec:
  selector:
    matchLabels:
      app: dcgm
  template:
    metadata:
      labels:
        app: dcgm
      annotations: # add annotation for prometheus scraping
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9400'
        prometheus.io/path: '/metrics' #default is /metrics

    spec:
      containers:
        - name: dcgm-container
          image: nvidia/dcgm-exporter:2.0.13-2.1.1-ubuntu18.04
          # switch default metrics to additional profiling metrics, not all gpu supported. if not support, container fatal error
          #args:
          #  - "-f=/etc/dcgm-exporter/dcp-metrics-included.csv"
          ports:
            - containerPort: 9400
          env:
            - name: DCGM_EXPORTER_INTERVAL
              value: "100"
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
