apiVersion: v1
kind: Pod
metadata:
    name: dali-gds-benchmark
spec:
  containers:
  - name: dali-gds-benchmark
    image:  centaurusinfra/torch-gds-basic:latest
    # image: cschranz/gpu-jupyter:v1.4_cuda-11.6_ubuntu-20.04_python-only
    env:
    - name: CUDA_VISIBLE_DEVICES
      value: 0,1,2,3          
    - name: PFLOG
      value: /log/pflog    
    - name: LD_PRELOAD
      value: /lib/interpose/libpfinterpose.so          
    ports:
      - containerPort: 8888
        name: jupyter-svc  
    # command: ["sh", "-c", "sleep infinity"]
    command: ["sh", "-c", "python resnet-cifar10-pytorch.py -cf 0 -g 1 --epochs 5"]
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /lib/interpose/
      name: intercept       
    - mountPath: /data
      name: data
    - name: pflog
      mountPath: /log/pflog 
  volumes:
  - name: dshm  # this is to trick pytorch when large size of shared memory is needed
    emptyDir:
      medium: Memory
  - name: intercept
    hostPath:
      path: /home/steven/dev/alnair/alnair-profiler/profiler-hook-lib/build/lib
      type: Directory
  - name: dali-example
    hostPath:
      path: /home/steven/dev/DataLoaders_DALI/
      type: Directory            
  - name: codes
    hostPath:
      path: /mnt/gds
      type: Directory      
  - name: data
    hostPath:
      path: /mnt/data
      type: Directory          
  - name: pflog
    hostPath:
      path: /var/lib/alnair/workspace/ 

