# permissions for end users to view alnairpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alnairpod-viewer-role
rules:
- apiGroups:
  - alnair.com.my.domain
  resources:
  - alnairpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alnair.com.my.domain
  resources:
  - alnairpods/status
  verbs:
  - get
