apiVersion: v1
kind: Pod
metadata:
  name: gan-mnist-demo
spec:
  containers:
  - name: tensorflow
    image: centaurusinfra/dcgan-demo
    command: ["python", "DCGAN_no_pic.py"]
    resources:
      limits:
        alnair/vgpu-memory: 8
        alnair/vgpu-compute: 100
  restartPolicy: OnFailure
