apiVersion: ai.centauruscloud.io/v1alpha1
kind: HorovodJob
metadata:
  name: sample
spec:
  launcherSpec:
    image: horovod/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.6.0.post0-py3.7-cuda10.1
    pythonCommand:
      - python
      - /examples/tensorflow2_mnist.py
  workersSpec:
    image: horovod/horovod:0.20.0-tf2.3.0-torch1.6.0-mxnet1.6.0.post0-py3.7-cuda10.1
    replicas: 3
      
