---
#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
  labels:
    name: host-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
#  mountOptions:
#  - "kernel_cache"
#  - "allow_other"
#  - "entry_timeout=36000"
#  - "attr_timeout=36000"
#  - "max_readahead=0"
  hostPath:
      path: /mnt/nikunj-test-hostpath-pv
---
#XapiVersion: v1
#Xkind: PersistentVolume
#Xmetadata:
#X  name: baremetal-alluxio-pv
#X  labels:
#X    name: baremetal-alluxio-pv
#Xspec:
#X  accessModes:
#X  - ReadWriteMany
#X  capacity:
#X    storage: 100Gi
#X#  mountOptions:
#X#  - "kernel_cache"
#X#  - "allow_other"
#X#  - "entry_timeout=36000"
#X#  - "attr_timeout=36000"
#X#  - "max_readahead=0"
#X  hostPath:
#X      path: /mnt/fuse/datasets
#X      type: Directory #OrCreate
