apiVersion: alnair.com/v1alpha1
kind: AlnairPod
metadata:
  name: imagenet-mini
  namespace: default
spec:
  secret:
    name: alnairpod-client-secret
  jobs:
  - name: job1
    image: zhuangweikang/imagenet:latest
    command: ["python3", "main.py"]
    datasource:
      name: ImageNet-Mini
      bucket: zhuangwei-bucket
      keys:
      - imagenet-mini/train
      - imagenet-mini/val
    configurations:
      usecache: true
      flushfreq: 10
      durabilityinmem: 120
      durabilityindisk: 1440
    tty: true
    stdin: true
